# Generated by Django 3.2 on 2021-04-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='last_name',
        ),
    ]
